### ISSUE TITLE
Inability to read the value I want

### ISSUE THREAD

**Issue by princess97** [pacificclimate/ncdf4.helpers#6]
Hello, I hope I'm writing in the right place. I'm trying to open a NetCDF file in R. I used the following codes functions. 
ncpath <- "C: / Users / xxx / Desktop / nc /"
> ncname <- "ECMWF_ERA-40_subset"
> ncfname <- paste (ncpath, ncname, ".nc", sep = "")
> dname <- "hcc"
> ncin <- nc_open (ncfname)
> print (ncin)
But I just want to see the "hcc" value. It shows all variables as output, do you think how can I solve thi

**Comment by jameshiebert** [comment]
You'll need to refer to the [`ncdf4` package docs]() as well as some [basic R documentation on lists and subsets](https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Lists-and-data-frames).
